title: Maria Jose Midence
email: mari_mide92@hotmail.com
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  name: "Maria Jose Midence"
  occupation: "Front-end Engineering Specialist"
  location:
    name: "Honduras"
    url: "https://maps.app.goo.gl/svwfGvtqpjMTVnMa9"

social:
  - url: "https://github.com/mmidence"
    title: "GitHub Profile Page"
    icon: "fab fa-github"
  - url: "https://www.linkedin.com/in/maria-midence-1702/"
    title: "LinkedIn Profile Page"
    icon: "fab fa-linkedin"  
